### ISSUE TITLE
Setup Milestones

### ISSUE THREAD

**Issue by bryantjderosier** [layars/layars-design-system#5]
Create the first couple milestones to keep track of work. These should include:

- [ ] Project Setup
- [ ] Props Alpha Release
- [ ] Icons Alpha Release
- [ ] Button Alpha Release
